Section 1
future4code/Gebru-landing-page1 pull request #2
Opened 2022-01-16 02:04 UTC by alineefraanca

Mockup será alterado posteriormente com a tela do notebook e do smartphone modificados.

![print_landing_section1](https://user-images.githubusercontent.com/92937108/149644453-981fa007-dab3-4108-98b7-5f8dfaeca5aa.jpeg)

2022-01-16 15:42 UTC, celiojunior0110 requested changes
Na linha 67 do css, para a altura da section ser do tamanho da página, o 'height' tem que ser 100vh, ao invés dos 500px. Tem como fazer essa alteração e dps dar commit?

2022-01-16 18:20 UTC, pepinodev requested changes
Só muda a altura para se ajustar à página. Linha 67, como o Célio disse.

2022-01-17 22:18 UTC, pepinodev approved these changes

2022-01-17 22:18 UTC, celiojunior0110 approved these changes

2022-01-17 22:20 UTC, merged